<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Обработка-и-анализ-данных-в-Numpy-массивах" data-toc-modified-id="Обработка-и-анализ-данных-в-Numpy-массивах-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Обработка и анализ данных в Numpy-массивах</a></span></li></ul></div>




# Обработка и анализ данных в Numpy-массивах

<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 1</p>

Дано: списки `a,b=[1,1,1],[3,3,3]`

Создать одномерные массивы A и B из списков а и b.

Вычислить выражение $-((B-А)*(B/2))$

In [2]:
import numpy as np

In [7]:
#1 Ваш код здесь
a,b=[1,1,1],[3,3,3]
A = np.array(a)
B = np.array(b)
c = -((B-A)*(B/2))
print(c)

[-3. -3. -3.]


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 2</p>

Используя как можно меньше операций в исходном массиве "шахматная доска" np.zeros((8,8)), добиться расстановки кодов "шахматных фигур".

Ожидаемый результат:
```
[[-4., -3., -2., -6., -5., -2., -3., -4.],
 [-1., -1., -1., -1., -1., -1., -1., -1.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [1., 1., 1., 1., 1., 1., 1., 1.],
 [4., 3., 2., 6., 5., 2., 3., 4.]]
 ```

In [29]:
#2. Ваш код здесь
board = np.zeros((8,8))
board[0,0] = -4  
board[0,1] = -3
board[0,2] = -2
board[0,3] = -6
board[0,4] = -5
board[0,5] = -2
board[0,6] = -3
board[0,7] = -4
board[1,:] = -1
board[6,:] = 1
board[7,0] = 4
board[7,1] = 3
board[7,2] = 2
board[7,3] = 6
board[7,4] = 5
board[7,5] = 2
board[7,6] = 3
board[7,7] = 4
print(board)

[[-4. -3. -2. -6. -5. -2. -3. -4.]
 [-1. -1. -1. -1. -1. -1. -1. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.]
 [ 4.  3.  2.  6.  5.  2.  3.  4.]]


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 3</p>

Средствами NumPy рассчитать произведения четных чисел от 2 до 20 на ближайшие к ним бОльшие нечетные числа

In [26]:
# 3. Ваш код здесь
massiv = np.arange(2,21,2)
nechet = np.arange(3,22,2)
result = massiv*nechet
print(result)


[  6  20  42  72 110 156 210 272 342 420]


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 4</p>

Сгенерировать двумерный массив *arr* размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в дипазоне от 0 до 20. Нормализовать значения массива так, что после нормализации максимальный элемент масива будет равен 1.0, минимальный 0.0. Значения округлить (с помощью `np.round()`) до четырех десятичных знаков.

In [6]:
# 4. Ваш код здесь
from numpy import random
x = random.randint(0,20, size=(4, 7))
print("массив", x)
print('')
norma = np.interp(x,(x.min(),x.max()), (0.0,1.0))
rount = np.round(norma)
print(rount)

массив [[ 9  4 15  6  9 14 19]
 [ 9 18 16  5  3 16 17]
 [ 2 17 12  0 18 16  5]
 [18 14  4 14  3  6 15]]

[[0. 0. 1. 0. 0. 1. 1.]
 [0. 1. 1. 0. 0. 1. 1.]
 [0. 1. 1. 0. 1. 1. 0.]
 [1. 1. 0. 1. 0. 0. 1.]]


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 5</p>

5. Имеется массив my_array
```
my_array = np.array([[1,2,3,4,5],
                [6,7,8,9,10],
                [11,12,13,14,15],
                [16,17,18,19,20],
                [21,22,23,24,25]])
```
Напишите код, с помощью которого можно извлечь из него центральный фрагмент размером 3 х 3, с числами 7, 8, 9, 12, 13, 14, 17, 18, 19.

In [2]:
# 5. Ваш код здесь

my_array = np.array([[1,2,3,4,5],
             [6,7,8,9,10],
             [11,12,13,14,15],
             [16,17,18,19,20],
             [21,22,23,24,25]])
print(my_array[1, 1:4])
print(my_array[2, 1:4])
print(my_array[3, 1:4])




[7 8 9]
[12 13 14]
[17 18 19]


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 6</p>

Создайте массив *my_sin*, состоящий из синусов элементов массива *my_array*.
Посчитайте, чему равна сумма элементов полученного массива. Ответ округлите до
трёх цифр после запятой.

In [3]:
# 6. Ваш код здесь
my_sin = np.sin(my_array)
sum = round(np.sum(my_sin),3)
print("Сумма элементов", sum)


Сумма элементов -0.058


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 7</p>

Создать матрицу из 20 случайных целых чисел от 0 до 100. Получить второе сверху значение в матрице. Определить индекс этого значения.

In [12]:
# 7. Ваш код здесь
from numpy import random
matrix = random.randint(100, size=(4,5))
print(matrix)
print("Вывод второго сверху")
print(matrix[0, 1])
print("Индекс значений")
for idx, val in np.ndenumerate(matrix):
    if val == matrix[0, 1]:
        print(idx)


[[47 51 78 19 39]
 [53 80 97 85 23]
 [22 25 89 72 35]
 [98  5 48 54 80]]
Вывод второго сверху
51
Индекс значений
(0, 1)


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 8</p>

Задать два двухмерных массива *ar1* и *ar2* размерности (4, 7), состоящих из случайных целых чисел в пределах от 0 до 10. Построить двухмерный массив размерности (4, 7), каждый элемент которого представляет собой максимум (минимум, среднее) из двух значений, находящихся на аналогичной позиции в массивах *ar1*, *ar2*.

In [48]:
# 8. Ваш код здесь
from numpy import random
ar1 = random.randint(0,10, size=(4,7))
ar2 = random.randint(0,10, size=(4,7))
maximum_result = np.maximum(ar1, ar2)
minimum_result = np.minimum(ar1, ar2)
average_result = (ar1+ar2)/2
print("ar1")
print(ar1)
print("ar2")
print(ar2)
print("max")
print(maximum_result)
print("min")
print(minimum_result)
print("sred")
print(average_result)


ar1
[[0 1 7 1 7 1 4]
 [1 9 8 3 7 6 9]
 [6 2 1 8 6 2 0]
 [7 0 3 8 8 1 2]]
ar2
[[2 2 2 6 7 2 9]
 [8 4 0 4 2 4 3]
 [2 8 9 8 1 1 7]
 [5 5 8 2 4 6 3]]
max
[[2 2 7 6 7 2 9]
 [8 9 8 4 7 6 9]
 [6 8 9 8 6 2 7]
 [7 5 8 8 8 6 3]]
min
[[0 1 2 1 7 1 4]
 [1 4 0 3 2 4 3]
 [2 2 1 8 1 1 0]
 [5 0 3 2 4 1 2]]
sred
[[1.  1.5 4.5 3.5 7.  1.5 6.5]
 [4.5 6.5 4.  3.5 4.5 5.  6. ]
 [4.  5.  5.  8.  3.5 1.5 3.5]
 [6.  2.5 5.5 5.  6.  3.5 2.5]]


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 9</p>

Имеется массив *great_array*
```
first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]
great_array = np.array([first, second, third]).T
```
Чему равна сумма элементов массива great_array, значение которых больше 50?

In [21]:
#9 Ваш код здесь

first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]
great_array = np.array([first, second, third]).T
raschet = np.sum(great_array[great_array>50])
print(raschet)




5470.0


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 10</p>

Переведите массив *great_array* в одномерную форму. Какое значение в получившемся массиве имеет элемент с индексом 150?

In [23]:
# 10. Ваш код здесь
odnomer = great_array.flatten()
print(odnomer[150])


7.0710678118654755


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 11</p>

Получить индексы, для которых элементы массивов A и B совпадают.
```
A = np.array([1,2,3,2,3,4,3,4,5,6])
B = np.array([7,2,10,2,7,4,9,4,9,8])
```
Ожидается результат:

```
array([1, 3, 5, 7])
```

In [30]:
# 11.

A = np.array([1,2,3,2,3,4,3,4,5,6])
B = np.array([7,2,10,2,7,4,9,4,9,8])

# Ваш код здесь
x = np.where(A==B)
print(x)


(array([1, 3, 5, 7], dtype=int64),)


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 12</p>

Создайте три массива: массив четных чисел от 2 до 20, массив ближайших к числам первого массива бОльших нечётных чисел, массив векторного произведения первого массива на второй. Соедините все массивы в один двумерный массив, расположив исходные массивы в столбцах.

In [3]:
# 12.  Ваш код здесь

