<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Обработка-и-анализ-данных-в-Numpy-массивах" data-toc-modified-id="Обработка-и-анализ-данных-в-Numpy-массивах-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Обработка и анализ данных в Numpy-массивах</a></span></li></ul></div>




# Обработка и анализ данных в Numpy-массивах

<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 1</p>

Дано: списки `a,b=[1,1,1],[3,3,3]`

Создать одномерные массивы A и B из списков а и b.

Вычислить выражение $-((B-А)*(B/2))$

In [13]:
import numpy as np

In [7]:
#1 Ваш код здесь
a,b=[1,1,1],[3,3,3]
A = np.array(a)
B = np.array(b)
c = -((B-A)*(B/2))
print(c)

[-3. -3. -3.]


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 2</p>

Используя как можно меньше операций в исходном массиве "шахматная доска" np.zeros((8,8)), добиться расстановки кодов "шахматных фигур".

Ожидаемый результат:
```
[[-4., -3., -2., -6., -5., -2., -3., -4.],
 [-1., -1., -1., -1., -1., -1., -1., -1.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [1., 1., 1., 1., 1., 1., 1., 1.],
 [4., 3., 2., 6., 5., 2., 3., 4.]]
 ```

In [8]:
#2. Ваш код здесь

board = np.zeros((8,8))

# Расстановка пешек
board[1::2, ::2] = 1
board[0::2, 1::2] = 1

# Расстановка ладей
board[0, 0] = 2
board[0, 7] = 2
board[7, 0] = 2
board[7, 7] = 2

# Расстановка коней
board[0, 1] = 3
board[0, 6] = 3
board[7, 1] = 3
board[7, 6] = 3

# Расстановка слонов
board[0, 2] = 4
board[0, 5] = 4
board[7, 2] = 4
board[7, 5] = 4

# Расстановка ферзя и короля
board[0, 3] = 5
board[0, 4] = 6
board[7, 3] = 5
board[7, 4] = 6

print(board)

[[2. 3. 4. 5. 6. 4. 3. 2.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [2. 3. 4. 5. 6. 4. 3. 2.]]


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 3</p>

Средствами NumPy рассчитать произведения четных чисел от 2 до 20 на ближайшие к ним бОльшие нечетные числа

In [9]:
# 3. Ваш код здесь



<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 4</p>

Сгенерировать двумерный массив *arr* размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в дипазоне от 0 до 20. Нормализовать значения массива так, что после нормализации максимальный элемент масива будет равен 1.0, минимальный 0.0. Значения округлить (с помощью `np.round()`) до четырех десятичных знаков.

In [16]:
# 4. Ваш код здесь
from numpy import random
x = random.randint(0,20, size=(4, 7))
print(x)

[[ 7 11  4 17 12  0 14]
 [14  2 16  0 11 14 16]
 [ 2  2 19 19  7 10 11]
 [17 12  9 12 17  5  2]]


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 5</p>

5. Имеется массив my_array
```
my_array = np.array([[1,2,3,4,5],
                [6,7,8,9,10],
                [11,12,13,14,15],
                [16,17,18,19,20],
                [21,22,23,24,25]])
```
Напишите код, с помощью которого можно извлечь из него центральный фрагмент размером 3 х 3, с числами 7, 8, 9, 12, 13, 14, 17, 18, 19.

In [11]:
# 5. Ваш код здесь

my_array = np.array([[1,2,3,4,5],
             [6,7,8,9,10],
             [11,12,13,14,15],
             [16,17,18,19,20],
             [21,22,23,24,25]])
print(my_array[1, 1:4])
print(my_array[2, 1:4])
print(my_array[3, 1:4])




[7 8 9]
[12 13 14]
[17 18 19]


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 6</p>

Создайте массив *my_sin*, состоящий из синусов элементов массива *my_array*.
Посчитайте, чему равна сумма элементов полученного массива. Ответ округлите до
трёх цифр после запятой.

In [12]:
# 6. Ваш код здесь



<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 7</p>

Создать матрицу из 20 случайных целых чисел от 0 до 100. Получить второе сверху значение в матрице. Определить индекс этого значения.

In [97]:
# 7. Ваш код здесь
from numpy import random
matrix = random.randint(100, size=(4,5))
print(matrix)
print("Вывод второго сверху")
print(matrix[0, 1])
print("Индекс значений")
'''
for idx, matrix in np.ndenumerate(matrix):
    print(idx, matrix)
    print(np.where(matrix==matrix[0, 1]))
'''
print(np.where(matrix == matrix[0, 1]))




[[31 52 17 75 51]
 [89 88 70 75 16]
 [26 86 33  4 98]
 [99 33 80 85 37]]
Вывод второго сверху
52
Индекс значений
(array([0], dtype=int64), array([1], dtype=int64))


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 8</p>

Задать два двухмерных массива *ar1* и *ar2* размерности (4, 7), состоящих из случайных целых чисел в пределах от 0 до 10. Построить двухмерный массив размерности (4, 7), каждый элемент которого представляет собой максимум (минимум, среднее) из двух значений, находящихся на аналогичной позиции в массивах *ar1*, *ar2*.

In [48]:
# 8. Ваш код здесь
from numpy import random
ar1 = random.randint(0,10, size=(4,7))
ar2 = random.randint(0,10, size=(4,7))
maximum_result = np.maximum(ar1, ar2)
minimum_result = np.minimum(ar1, ar2)
average_result = (ar1+ar2)/2
print("ar1")
print(ar1)
print("ar2")
print(ar2)
print("max")
print(maximum_result)
print("min")
print(minimum_result)
print("sred")
print(average_result)


ar1
[[0 1 7 1 7 1 4]
 [1 9 8 3 7 6 9]
 [6 2 1 8 6 2 0]
 [7 0 3 8 8 1 2]]
ar2
[[2 2 2 6 7 2 9]
 [8 4 0 4 2 4 3]
 [2 8 9 8 1 1 7]
 [5 5 8 2 4 6 3]]
max
[[2 2 7 6 7 2 9]
 [8 9 8 4 7 6 9]
 [6 8 9 8 6 2 7]
 [7 5 8 8 8 6 3]]
min
[[0 1 2 1 7 1 4]
 [1 4 0 3 2 4 3]
 [2 2 1 8 1 1 0]
 [5 0 3 2 4 1 2]]
sred
[[1.  1.5 4.5 3.5 7.  1.5 6.5]
 [4.5 6.5 4.  3.5 4.5 5.  6. ]
 [4.  5.  5.  8.  3.5 1.5 3.5]
 [6.  2.5 5.5 5.  6.  3.5 2.5]]


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 9</p>

Имеется массив *great_array*
```
first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]
great_array = np.array([first, second, third]).T
```
Чему равна сумма элементов массива great_array, значение которых больше 50?

In [3]:
#9 Ваш код здесь

first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]
great_array = np.array([first, second, third]).T
print(great_array)





[[ 0.          4.64158883 66.66666667]
 [ 1.          4.65700951 40.        ]
 [ 1.41421356  4.67232873 67.33333333]
 [ 1.73205081  4.68754815 40.4       ]
 [ 2.          4.70266938 68.        ]
 [ 2.23606798  4.71769398 40.8       ]
 [ 2.44948974  4.73262349 68.66666667]
 [ 2.64575131  4.7474594  41.2       ]
 [ 2.82842712  4.76220316 69.33333333]
 [ 3.          4.77685618 41.6       ]
 [ 3.16227766  4.79141986 70.        ]
 [ 3.31662479  4.80589553 42.        ]
 [ 3.46410162  4.82028453 70.66666667]
 [ 3.60555128  4.83458813 42.4       ]
 [ 3.74165739  4.84880759 71.33333333]
 [ 3.87298335  4.86294413 42.8       ]
 [ 4.          4.87699896 72.        ]
 [ 4.12310563  4.89097325 43.2       ]
 [ 4.24264069  4.90486813 72.66666667]
 [ 4.35889894  4.91868473 43.6       ]
 [ 4.47213595  4.93242415 73.33333333]
 [ 4.58257569  4.94608744 44.        ]
 [ 4.69041576  4.95967566 74.        ]
 [ 4.79583152  4.97318983 44.4       ]
 [ 4.89897949  4.98663095 74.66666667]
 [ 5.          5.        

<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 10</p>

Переведите массив *great_array* в одномерную форму. Какое значение в получившемся массиве имеет элемент с индексом 150?

In [29]:
# 10. Ваш код здесь



<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 11</p>

Получить индексы, для которых элементы массивов A и B совпадают.
```
A = np.array([1,2,3,2,3,4,3,4,5,6])
B = np.array([7,2,10,2,7,4,9,4,9,8])
```
Ожидается результат:

```
array([1, 3, 5, 7])
```

In [30]:
# 11.

A = np.array([1,2,3,2,3,4,3,4,5,6])
B = np.array([7,2,10,2,7,4,9,4,9,8])

# Ваш код здесь
x = np.where(A==B)
print(x)


(array([1, 3, 5, 7], dtype=int64),)


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 12</p>

Создайте три массива: массив четных чисел от 2 до 20, массив ближайших к числам первого массива бОльших нечётных чисел, массив векторного произведения первого массива на второй. Соедините все массивы в один двумерный массив, расположив исходные массивы в столбцах.

In [3]:
# 12.  Ваш код здесь

